### ISSUE TITLE
Bypass collection phase if Control Center is not started

### ISSUE THREAD

**Issue by silviuFlorin** [mozilla/iris2#138]
Currently Collection phase code is reached even though Control Centre is not started. As a consequence all patterns are loaded and it takes a lot of time to debug a single test.

**Comment by mwobensmith** [comment]
@silviuFlorin Hmmm, are you sure about this? After further inspection, I don't think the collection happens without the Control Center code being invoked. I just added some logging in `create_target_json` that demonstrates this.

I do see the large amount of pattern lookups,  and I think this is due to the fact that we are importing some core and helper code that references a lot of patterns. 

There seem to be two places during startup where we see this happening. 

1. In `__main__.py`, line 71, we import the selected target module, which - for Firefox - imports:

```
from targets.firefox.firefox_ui.helpers.version_parser import check_version
```

2. The second  is caused by these imports in `fx_testcase.py`:

```
from targets.firefox.firefox_ui.helpers.general import *
from targets.firefox.test_dependencies import *
```

I don't recall this performance issue in Iris 1.0, so I am not sure why we see it now.

I don't know if we can work around the first part, but for the second, an alternative would be to **not** import `firefox_ui` and `local_web` into `fx_testcase.py`. However, that would remove the convenience for test cases.

Do you agree with the above? If so, maybe the problem here is that our pattern lookup itself could be optimized.

**Comment by silviuFlorin** [comment]
@mwobensmith : After a closer look it seems that everything behaves as expected. All the firefox_ui patterns are loaded before test execution and application specific patterns are not mixed up (this was fixed in the meantime). We can close this issue
