### ISSUE TITLE
targets.json does not collect data for newly created suites/test cases

### ISSUE THREAD

**Issue by icrisan** [mozilla/iris2#284]
Steps to reproduce:
1. Add a new test directory(e.g: search)
2. Add some test case coverage
3. Open CC from the terminal(pipenv run iris firefox -k)

Expected results:
CC opens and the newly added test suite/test cases are displayed. 

Actual results:
CC opens and the newly added test suite/test cases are **NOT** displayed.

**Comment by psilaghi** [comment]
Server side issue.
Note that if deleting target.json and then running "iris -k", the newly generated target.json contains all the recently added tests and CC displays them fine, too.

**Comment by pavelciapa** [comment]
@psilaghi  please clarify **full path** to file `target.json` which needs to be deleted. Can't find one in project folder. Thanks

**Comment by psilaghi** [comment]
c:\Users\paul.silaghi\.iris\data\targets.json

**Comment by pavelciapa** [comment]
> 
> 
> c:\Users\paul.silaghi\.iris\data\targets.json

Thank you, but still it didn't solve the issue for me. I deleted a file but I see empty list of tests when I run  Iris

**Comment by mwobensmith** [comment]
There is a feature in Iris right now where we cache the JSON used by the Control Center. This means that we don't write a new targets.json file unless 15 minutes has gone by. This is to save time when you are constantly launching the Control Center, instead of waiting up to one extra minute for Iris to generate the JSON data. If you delete this file - as @psilaghi says - this will force Iris to regenerate it and you should see all of the installed tests. If that does not happen, it could be a bug, but I'm not aware of it.

**Comment by pavelciapa** [comment]
After investigation I found that having this preference:
**tests/firefox/privacy/no_browsing_download_history.py**
```
        set_profile_pref={
                          'browser.download.dir': IrisCore.get_downloads_dir(),

```
I got blank test list. No matter if I deleted` target.json` or not. After comment out this line in this test and deleting `target.json` I got full test list

**Comment by pavelciapa** [comment]
>         set_profile_pref={
>                           'browser.download.dir': **IrisCore.**get_downloads_dir(),

is that ok when non-declared property causes Control Center to show empty test list?

**Comment by mwobensmith** [comment]
That sounds like a bug.

**Comment by mwobensmith** [comment]
Captured bug in #324 - thanks @pavelciapa
